### ISSUE TITLE
PDF report preview

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#17]
When I go to this the default setting is for a Manhole Report only, which is fine, but there is an image on the title page which shouldn't be there. If I look at the preview in Asset or Complete view then this image is not present.

**Comment by armandomusto** [comment]
This is the first page of Manhole report
![image](https://cloud.githubusercontent.com/assets/4960206/10098813/6d4cc4da-6384-11e5-9040-76290b7f7ee5.png)

This is the first page of Asset Report
![image](https://cloud.githubusercontent.com/assets/4960206/10098829/79d4ee30-6384-11e5-8119-b32d5b2909bc.png)

This is the first page of complete report
![image](https://cloud.githubusercontent.com/assets/4960206/10098841/8ad7786a-6384-11e5-971c-cdca64d18a3b.png)


I cannot see any image on title page

**Comment by armandomusto** [comment]
Please send me a screenshot, I am not able to replicate

**Comment by Viewline-MH** [comment]
Will do. Have you got any pictures in your project. The image I'm seeing is
part of an image I have in the report.

Regards,

Ian.






*www.viewline.tv* <http://www.viewline.tv/>

t: (+44) 01752 358142
m. 07722 161 232
m. 07961 736 412

Viewline, Eurotech House, Burrington Ind. Est., Plymouth. PL5 3LZ

**Comment by armandomusto** [comment]
Fixed. It will be available in the next release.
