### ISSUE TITLE
Asset reports and picture files from drive

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#26]
Creation of Asset 1 and adding a picture file from a drive to Location Photograph and Condition Photograph. I can see the pictures on the UI but if I return to the Project list and then reopen that Asset Report the pictures have gone.

ALSO

Creation of Asset 1 and adding a picture file from a drive to Location Photograph and Condition Photograph. I can see the pictures on the UI for Asset 1, THEN I create Asset 2 and the pictures from Asset 1 are shown on Asset 2. Close down and reopen and these pictures have gone from both assets.

**Comment by armandomusto** [comment]
The bug related to load a picture from drive has been fixed. Anyway each time the user apply a change to the data, it should be saved otherwise the changes will disappears

**Comment by Viewline-MH** [comment]
The picture loading issue is resolved. There is an issue concerning adding duplicate node references that I will expand upon as a new issue.
