### ISSUE TITLE
Asset Photographs

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#28]
Deleting photographs not working. Although the image disappears from the UI, when the project is closed out of and back in the photographs are still there.

**Comment by Viewline-MH** [comment]
This is the case in both Photographs and Remarks and Additional photographs.

**Comment by armandomusto** [comment]
When you change a value of an Asset, or Manhole you need to save it if you want to make that change permanent. I fixed the behaviour of application, not it raises a warning if you want quit without save.
