### ISSUE TITLE
Release 12

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#29]
Unable to install. Error stopping installation.

**Comment by armandomusto** [comment]
Can you send me a screenshot please?

**Comment by Viewline-MH** [comment]
I'll try.






*www.viewline.tv* <http://www.viewline.tv/>

t: (+44) 01752 358142
m. 07722 161 232
m. 07961 736 412

Viewline, Eurotech House, Burrington Ind. Est., Plymouth. PL5 3LZ

**Comment by Viewline-MH** [comment]
Apologies. I didn't realise there was a new release. Just downloaded and
installed with no problems.

I'll test today.

Regards,

Ian.






*www.viewline.tv* <http://www.viewline.tv/>

t: (+44) 01752 358142
m. 07722 161 232
m. 07961 736 412

Viewline, Eurotech House, Burrington Ind. Est., Plymouth. PL5 3LZ
