### ISSUE TITLE
Photographs Generally

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#31]
I can't test any of the photograph issues. This seems not to be working now in manholes and assets. I can't see a preview to take a photo and then I can't exit. The only option to continue seemed to be closing out and then back into the app. Although I did notice that after a fairly long period, maybe 2 or 3 minutes after hitting the Exit button, the  camera pane closed and I was returned back to Photograph tab.

**Comment by armandomusto** [comment]
I tested it with my lòaptop and it is working fine. I will also try using the tablet.

**Comment by armandomusto** [comment]
Can you test on your laptop? Can you also test on a different tablet?

**Comment by Viewline-MH** [comment]
I can test on my laptop, testing on another tablet is problematic. It's odd because the photograph taking part was working very well.

**Comment by armandomusto** [comment]
I think the issue is related to the tablet, bacause on laptop and desktop it is working fine.

**Comment by Viewline-MH** [comment]
It's not working on my laptop. No feed from webcam and caused it to freeze. Had to ctrl, alt, del to get to the task manager and close it down.

**Comment by armandomusto** [comment]
Which O.S. did you install on your machine?

**Comment by Viewline-MH** [comment]
They both have Windows 10. Like I said previously the photo module was working fine on the tablet prior to the latest release.

**Comment by armandomusto** [comment]
It is working fine on my side...I will double check also on another laptop

**Comment by Viewline-MH** [comment]
It works fine on my home PC which is Windows 7. Recently both my tablet and work PC updated and I did notice some slight changes in the operation of both. This may have happened in between releases.

**Comment by Viewline-MH** [comment]
Have you tested on Win 10 ?

**Comment by Viewline-MH** [comment]
Have you had an update?

**Comment by armandomusto** [comment]
Do you man an update of the O.S.? Are you sure your cameras are working fine?

**Comment by Viewline-MH** [comment]
I'm sure the cameras are fine on both.

**Comment by armandomusto** [comment]
I tested right now on another laptop with Windows 7 and also on desktop with Win10 and it works fine.

**Comment by Viewline-MH** [comment]
Yes, it's odd. Sounds like it's my office machines. I'll check them tomorrow. Do you know if the Win 10 machine has updated recently? Everything is looking good though on 7.

**Comment by armandomusto** [comment]
Win 10 got bit update at the beginning of this week. But as I told you it is working fine on my Win 10 machine

**Comment by Viewline-MH** [comment]
Testing this on work laptop Win 10. I see the webcam is selected but no image is shown. Trying to work out why.

![image](https://cloud.githubusercontent.com/assets/13435677/11395426/dcdefb0c-9362-11e5-871a-1527bb7b79f4.png)

**Comment by Viewline-MH** [comment]
I am going around a friend's house for lunch around 1pm. I'll check on his laptop and tablet. Both Win 10. Should report back about 2 hours afterwards.

**Comment by armandomusto** [comment]
What do you think if I update my table to Win10? I think we should provide the software for Win 10 O.S., Win 8.1 is going to be replaced at all.

**Comment by Viewline-MH** [comment]
Definitely.

**Comment by Viewline-MH** [comment]
It worked on my friends machine and my tablet after I refreshed the operating system. So it is fine on Windows 10. Not sure why my work laptop is not playing. While I was on the Win 10 machines I did some further testing and noted a few issues. I'll detail them here as normal.
