### ISSUE TITLE
Adding black and white images from file.

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#32]
This is weird. I add a raster image from file of a site plan, say in Location Sketch. Then I add another in say Plan of manhole and the image I added in Location sketch is obscured by a grey rectangle with a regular dark pattern.

**Comment by armandomusto** [comment]
Add a screenshot please

**Comment by Viewline-MH** [comment]
That is not the easiest with a tablet. Do you know how to?

**Comment by armandomusto** [comment]
I think there are some issue using that control with the tablet. I will test and let you know.

**Comment by Viewline-MH** [comment]
![imag0511](https://cloud.githubusercontent.com/assets/13435677/11368784/7aeba60c-92b3-11e5-8bf5-47f47d11c593.jpg)

**Comment by Viewline-MH** [comment]
![image](https://cloud.githubusercontent.com/assets/13435677/11378864/3c31c9a0-92e5-11e5-926c-48d052d1606d.png)
So I get the same on my Win 7 machine but only on specific images. I've attached the image that goes grey when the Save button is used. Try it on your end.
![vl010](https://cloud.githubusercontent.com/assets/13435677/11379114/822f72b2-92e6-11e5-9fd8-6657c9c4bf87.jpg)

**Comment by armandomusto** [comment]
Yes you are right, it is very strange because it happens only with that image. Unfortunately I cannot do anything becuase those functionalities (open, deleting, copy and paste) are hard coded inside the control and I connot change them

**Comment by Viewline-MH** [comment]
Okay, that's not too much of a problem. At least I know it might do this.
