### ISSUE TITLE
New Manhole, New Asset.

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#36]
It is possible just after creation of a new manhole to enter data and click the Asset icon on the bottom bar without any warning concerning saving. If this is done data is lost/not saved.

It is also the case after creation of a new asset and entering data to click the Manhole icon on the bottom bar that I can move to the Manhole form without a warning concerning saving. Data can be lost/not saved.

This only occurs immediately after initial creation of either. If an existing Asset or Manhole has been saved and returned to and data is entered or changed then click on the appropriate icon in the bottom bar gives the required warning.

**Comment by armandomusto** [comment]
We already knew this issue and  working to solve it.

**Comment by armandomusto** [comment]
Done
