### ISSUE TITLE
PDF Report output

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#38]
The pictures that have been saved for a manhole report are not showing correctly in the report. I think what is happening is the images are being saved full size to the database and then when used to populate the PDF they are not being squeezed down to picture frame size. 

It might be a better option (for a number of reasons) to save images and squeeze them down to the eventual report output size and then save them in the database. This would reduce the size of the database, prevent this issue and speed up rendering?

I think you have reduced the picture size to get those pictures into that area of white space, which is exactly what is required but it's still not enough.

**Comment by Viewline-MH** [comment]
This issue has changed in that now when I am viewing the PDF report, I can see a zoomed in section of the picture only, very much like the picture has been cropped.

**Comment by Viewline-MH** [comment]
I'm still seeing this in the Manhole section of the PDF report but I noticed that the Asset pictures look correct. That should make life easier.

**Comment by armandomusto** [comment]
It will be available in the next release
