### ISSUE TITLE
XML import

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#39]
This doesn't work. I'm not sure why.

**Comment by armandomusto** [comment]
You have to specify what does not work. Create a project using the software from a desktop machine then export and import into your tablet.

**Comment by Viewline-MH** [comment]
Will do.

**Comment by Viewline-MH** [comment]
I'm finding nothing happens. I created an xml file on my laptop and then imported from my tablet and nothing happened. I'll try that in reverse from tablet to laptop.

**Comment by Viewline-MH** [comment]
Yes, definitely not happening. I can create the file and it looks good but import doesn't seem to work. I can navigate to the XML file and click Open but nothing happens.

**Comment by Viewline-MH** [comment]
Tested thoroughly and not working. Exporting XML files from Tablet, importing same to PC and nothing happens.

**Comment by Viewline-MH** [comment]
Created XML file export on one machine and imported into MH report on another and I thought it had worked but no. A project was created but no data was present; no manhole or asset information. I checked the exported file and there was data.
