### ISSUE TITLE
Details/Cover/Cover level

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#45]
This number needs to be to one decimal place 000.0

**Comment by armandomusto** [comment]
Do you want all the decimal numbers have only one decimal position?

**Comment by Viewline-MH** [comment]
No, only the measurements that are to a the metre (m) should be to one decimal place. Measurements that are by mm would have no decimal point.

**Comment by Viewline-MH** [comment]
Sorry but I made a mistake here. It should be two decimal places 00.00

**Comment by armandomusto** [comment]
Meter should be two decimal places 00.00 and mm zero decimal places, right?

**Comment by Viewline-MH** [comment]
Yes, that's right.
