### ISSUE TITLE
Manhole data

### ISSUE THREAD

**Issue by armandomusto** [armandomusto/Manhole-Report#6]
Northing and Easting (Location tab) can both use the numeral pad.

On INCOMING PIPES,  the Levels tab, I think it would be better if the fields Cover Level (m) and Construction Code should be in the Dimensions/Cover tab. 

On INCOMING PIPES the depth should be to 2 decimal places (1.60) and the INVERT LEVEL can also use the number pad rather than the keyboard.

In INCOMING PIPES the column Pipe Size (mm)Width is spelt incorrectly.

Obviously there’s a major issue with creating or editing an Incoming Pipe or an Outgoing Pipe (in fact just clicking the ‘+’ to add a new pipe and then cancelling causes it), it seems to create duplicate information in all the other tabs for already created Manholes.
On New Outgoing you’ve put OUTCOMING.  The Invert Level can be entered using a number pad.

**Comment by armandomusto** [comment]
Fixed. All the issues will be solved with the next release.

**Comment by Viewline-MH** [comment]
Excellent. I am away for the weekend. Taking son to university.
Regards,
Ian.

**Comment by armandomusto** [comment]
A new release has been uploaded. Please test.
If the test is passed please close the issue, otherwise add a new comment and assign the issue to me again.

**Comment by Viewline-MH** [comment]
Every part of this issue has been fixed apart from the major issue on the last paragraph. When an Incoming Pipe or Outgoing pipe is added to a manhole all the manholes in that project are suddenly populated with the information with that manholes data. It's pretty major.

**Comment by armandomusto** [comment]
Fixed. It will be available with the next release.
