### ISSUE TITLE
Photo size

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#65]
I get a message on some photos saying they have exceeded the 2Mb limit but these photos are less than 2 Mb . It seems any photo over 1.7Mb won't be accepted.

**Comment by armandomusto** [comment]
Please send me an example
Il 24/Gen/2016 15:41, "Viewline-MH" <notifications@github.com> ha scritto:

**Comment by Viewline-MH** [comment]
![dscf2263](https://cloud.githubusercontent.com/assets/13435677/12544048/e86b95e8-c32d-11e5-9ec0-a9d68142ab0c.JPG)

**Comment by armandomusto** [comment]
Fixed. Are you fine with 2MB limit? Or do you want it configurable?

**Comment by Viewline-MH** [comment]
Probably an idea to make it configurable, reduces potential problems.

**Comment by armandomusto** [comment]
Ok but with an upper limit of 5MB

**Comment by Viewline-MH** [comment]
Yes, that would be fine.






*www.viewline.tv* <http://www.viewline.tv/>

t: (+44) 01752 358142
m. 07722 161 232
m. 07961 736 412

Viewline, Eurotech House, Burrington Ind. Est., Plymouth. PL5 3LZ

**Comment by Viewline-MH** [comment]
I can't adjust the max image import size, no keyboard pops up on selection.
