### ISSUE TITLE
Projects button

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#66]
I was expecting that if I clicked on this button it would take me to the projects list but it doesn't, should it?

**Comment by armandomusto** [comment]
The Projects button is already selected when you are in MOnhole,Asset or Report.
What we can do is to add a new botton at the bottom to go back to the Projects view

**Comment by Viewline-MH** [comment]
Yes, if you could, I think that's a good idea if you agree. Thanks.
