### ISSUE TITLE
PDF report output layout

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#68]
This looks really good but I noticed in the Cover/shape field if I select Circular or Rectangular, the last letters wrap down to the next line because the box isn't long enough. Can we make this shrink to fit or increase the length to account for the longest word?

**Comment by armandomusto** [comment]
We can only fit it manually trying to obtain the best result, it is not possible to select an autosize behaviour

**Comment by Viewline-MH** [comment]
So shrinking the text is one option or making the box slightly longer. I'm easy with either.
