### ISSUE TITLE
Alphabetically referencing Incoming and Outgoing pipes.

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#70]
This is something that was part of the original program and has been missed by both of us but it is my responsibility and thus I see it as an additional. It is an important aspect that needs to be added to the Incoming and Outgoing pipes, I shall explain.
When adding incoming pipes they should each have a reference letter. The first incoming pipe added is referenced 'A', the second pipe 'B', the third 'C' and so on. This would be as simple as adding an additional field and auto populating with each letter as the Incoming pipe is added. This would need to be visible on the input form and the output PDF. I have attached an example that will clarify this.
When adding outgoing pipes the same process applies but as you can imagine there is normally only one and that would be referenced 'X', if there were a second it would be 'Y' and finally in the unlikely event of there being a third outgoing pipe, that would be 'Z'. The picture below will make sense.
![stc25](https://cloud.githubusercontent.com/assets/13435677/12964976/e3f65b22-d04a-11e5-8f37-73b24280268c.jpg)

**Comment by armandomusto** [comment]
Implemented, please test

**Comment by Viewline-MH** [comment]
Excellent.
