### ISSUE TITLE
AutoSave functionality

### ISSUE THREAD

**Issue by armandomusto** [armandomusto/Manhole-Report#8]
I’m wondering if it shouldn’t auto save, rather than having to remember to save or at least warning the user if they need to save the existing when touching the New button or closing the program.

**Comment by armandomusto** [comment]
I don't think it is a good idea. We can add a waring to advice user that data are changed and if they want to save

**Comment by Viewline-MH** [comment]
Sorry for the delay Armando. Development of another project is nearing
completion and requires some intense testing.

Regards,

Ian.






*www.viewline.tv* <http://www.viewline.tv/>

t: (+44) 01752 358142
m. 07722 161 232
m. 07961 736 412

Viewline, Eurotech House, Burrington Ind. Est., Plymouth. PL5 3LZ

**Comment by Viewline-MH** [comment]
Hi Armando,

I can't install the latest release (v 12).

Can you package another installer please?

Regards,

Ian.






*www.viewline.tv* <http://www.viewline.tv/>

t: (+44) 01752 358142
m. 07722 161 232
m. 07961 736 412

Viewline, Eurotech House, Burrington Ind. Est., Plymouth. PL5 3LZ
