### ISSUE TITLE
Asset view

### ISSUE THREAD

**Issue by armandomusto** [armandomusto/Manhole-Report#9]
It’s the same on the ASSET FORM. When New is selected the ASSET CREATION form should open with the keyboard showing. Pressing Enter or Close should save the data and close the form revealing the  ASSET REPORT form just created ready to be populated. I see the OK button now, which does this job but Enter and Close should do the same job.

There’s an issue with Additional Photographs in that the same picture thumbnail is shown in every Additional photograph tab for each asset.

Asset count not counting.

There should be the Project Name on the ASSET REPORTS.

Asset Description/Data: Node Type not working.  Dimensions, Cover level, Depth (m) won’t let me enter a decimal point. Surface make up has the word Tarmac spelt incorrectly and doesn’t work.
Outfall Pipe Diameter will be a number, so the number keypad would be good for this one.
In Asset Description/Data there is a a field labelled Outfalls to (mm). It should read Outfalls to: and the information will be text and numbers , so the keyboard is required. Also Cover level should be to 2 decimal places.

The PDF report is excellent. It would be better if the Visual report started immediately after the Data report. There is no need for a page break there.

**Comment by armandomusto** [comment]
Fixed, It will be available in the next release

**Comment by armandomusto** [comment]
A new release has been uploaded. Please test.

**Comment by Viewline-MH** [comment]
Everything is fixed, apart from the Additional Photograph issue. The issue here is that additional photos added to one asset also seem to populate the Additional Photos tabs of other assets.

**Comment by armandomusto** [comment]
Fixed. It will be available with the next release.
